### ISSUE TITLE
topic issues

### ISSUE THREAD

**Issue by kurniawan77** [rorist/sk6812-ws2812fx-mqtt-esp8266#1]
hi,

somehow, i can only get this working with HomeAssistant if i set both the state_topic and command_topic the same:
configuration.yaml
```
  - platform: mqtt_json
    name: bookshelves_leds
    state_topic: "bookshelves/leds/set"
    command_topic: "bookshelves/leds/set"

```
config.h:
```
// MQTT Topics
#define CONFIG_MQTT_TOPIC_STATE "bookshelves/leds"
#define CONFIG_MQTT_TOPIC_SET "bookshelves/leds/set"
#define CONFIG_MQTT_PAYLOAD_ON "ON"
#define CONFIG_MQTT_PAYLOAD_OFF "OFF"
```
Dont know why this go wrong? Any ideas?

**Comment by rorist** [comment]
Hi,

You need both topics but they have to be different, it doesn't work when they are something like this?:

```
    state_topic: "bookshelves/leds"
    command_topic: "bookshelves/leds/set"
```

That's the setup I have, maybe you can try to get all mqtt messages (`mosquitto_sub -V mqttv311 -u homeassistant -P yourpass -v -h 192.168.x.x -p 1883 -t '#'`) and see if there's something strange, and also take a look at the `home-assistant.log` file.

**Comment by kurniawan77** [comment]
I have done as suggested and also subscribed to "bookshelves/leds" on the network. What I have noticed is that i dont see any state_topic changes from my device. It keeps saying:
`bookshelves/leds {"color":{"r":60,"g":0,"b":0},"white_value":58,"state":"ON","brightness":98,"effect":"Sparkle","speed":1}`

I can turn the leds on with:
 mosquitto_pub -t bookshelves/leds/set -m {\"state\":\"ON\"}

and off:
 mosquitto_pub -t bookshelves/leds/set -m {\"state\":\"OFF\"}

but the state_topic never changes

**Comment by kurniawan77** [comment]
I have done as suggested and also subscribed to "bookshelves/leds" on the network. What I have noticed is that i dont see any state_topic changes from my device. It keeps saying:
`bookshelves/leds {"color":{"r":60,"g":0,"b":0},"white_value":58,"state":"ON","brightness":98,"effect":"Sparkle","speed":1}`

I can turn the leds on with:
`mosquitto_pub -t bookshelves/leds/set -m {\"state\":\"ON\"}`

and off:
`mosquitto_pub -t bookshelves/leds/set -m {\"state\":\"OFF\"}`

but the state_topic never changes

**Comment by kurniawan77** [comment]
and by the way... all of my other mqtt devices are working properly...

I am using a Wemos D1 mini for this project.

If i do a pub to the state_topic "bookshelves/leds" with:
`mosquitto_pub -t bookshelves/leds -m {\"state\":\"ON\"}`

then in HA the "light" goes on and then i can change the brightness and also get the color wheel... small workaround for me... but still doesnt work properly as the device doesn't send any update on the state_topic

**Comment by kurniawan77** [comment]
Alright, i nailed it.

in PubSubClient.h i changed MQTT_MAX_PACKET_SIZE to 512 and it works!
